### ISSUE TITLE
Trezor Crashes the App

### ISSUE THREAD

**Issue by Fible1** [dashpay/electrum-dash#1]
Ubuntu 15.10; System 76 galago ultrapro; 16 gigs ram.
Encompass works fine.

pablo@System76:~/Desktop/electrum-dash$ ./electrum-dash
./electrum-dash: line 3: cd: /home/pablo/electrum-dash: No such file or directory

(electrum-dash-x86_64.bin:15278): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(electrum-dash-x86_64.bin:15278): Gtk-WARNING **: Loading IM context type 'ibus' failed

(electrum-dash-x86_64.bin:15278): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(electrum-dash-x86_64.bin:15278): Gtk-WARNING **: Loading IM context type 'ibus' failed

(electrum-dash-x86_64.bin:15278): Gtk-WARNING **: GModule (/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-ibus.so) initialization check failed: GLib version too old (micro mismatch)

(electrum-dash-x86_64.bin:15278): Gtk-WARNING **: Loading IM context type 'ibus' failed
Error: cannot initialize plugin trezor
Traceback (most recent call last):
  File "/tmp/_MEI5ob99W/gui/qt/__init__.py", line 163, in run_wizard
    wallet = wizard.run(action, wallet_type)
  File "/tmp/_MEI5ob99W/gui/qt/installwizard.py", line 447, in run
    action = wallet.get_action()
AttributeError: 'NoneType' object has no attribute 'get_action'

**Comment by Kefkius** [comment]
Could you try this again with [v2.4.1rc2](https://github.com/mazaclub/electrum-dash/releases)?

**Comment by Fible1** [comment]
Works now, nice job.

Pablo.

On Tue, Dec 8, 2015 at 10:22 PM, Kefkius <notifications@github.com> wrote:

> Could you try this again with v2.4.1rc2
> <https://github.com/mazaclub/electrum-dash/releases>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mazaclub/electrum-dash/issues/1#issuecomment-163085978>
> .
>



-- 
PGP Key(s):

Pablo@Pablo-Lema.com: *http://pastebin.com/V8Z4WxUE
<http://pastebin.com/V8Z4WxUE>*

Our company accepts no liability for the content of this email, or for the
consequences of any actions taken on the basis of the information provided,
unless that information is subsequently confirmed in writing.

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by schinzelh** [comment]
fixed in v2.4.1rc2
