### ISSUE TITLE
Ledger Nano S Not Working

### ISSUE THREAD

**Issue by joesixpack** [dashpay/electrum-dash#1]
Works fine on regular Electrum.

![image](https://user-images.githubusercontent.com/23145642/33374049-525fac20-d4b9-11e7-84e2-5ddc89a5ab2d.png)

**Comment by sedited** [comment]
Seems like it all that is missing are upstream changes. If the changes are incorporated the wallet will support Ledger and Digital Bitbox.

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
