### ISSUE TITLE
Unable to import extended keys in new wallet creation dialog.

### ISSUE THREAD

**Issue by nmarley** [dashpay/electrum-dash#15]
The "next" button is just grayed out/disabled, doesn't enable when I paste in an xprv or an xpub key.

**Comment by Kefkius** [comment]
Is this because of #7 (i.e. what do the extended keys start with)?

**Comment by nmarley** [comment]
No, I don't think so. I haven't dived into why this isn't working.

**Comment by nmarley** [comment]
Ok, this is working for me now, closing this issue. I expected Electrum to allow sub-keys entered instead of only the master xpub/xprv keys, but apparently it won't accept child keys, only the master.

**Comment by nmarley** [comment]
Nevermind! You were right @Kefkius , this is exactly because I wasn't running the right local version of Electrum — I was using my drk* branch instead. It *does* work with sub-keys as well as master keys.
