### ISSUE TITLE
Could you help to pull new security fix changes from electrum team?

### ISSUE THREAD

**Issue by jasonOramo** [dashpay/electrum-dash#2]
Could you help to pull new security fix changes from electrum team? 
There is a JSON-RPC security issue in the electrum wallet and electrum team already released 3.0.5 version to fix it.

**Comment by nmarley** [comment]
Hi, thanks for bringing this up. Current development on Electrum-Dash is done at this repo, where this issue has been addressed in a timely manner: https://github.com/akhavr/electrum-dash

**Comment by nmarley** [comment]
Closing per above ^
