### ISSUE TITLE
Rebase onto Electrum 2.6

### ISSUE THREAD

**Issue by ashmoran** [dashpay/electrum-dash#23]
I use both Electrum-Bitcoin and Electrum-Dash and I noticed Electrum-Dash is a couple of minor versions behind the Bitcoin version.

The biggest changed for me (from the [release notes](https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES)) is _Much improved support for TREZOR and KeepKey devices_. It also features *Alternative coin selection policy, designed to help preserve user privacy*, which is less of an advantage with Dash, but is still a welcome addition for privacy when not using PrivateSend.

These features would be nice to have, but I imagine it might be time consuming to merge changes from Electrum-Bitcoin 2.5 and 2.6, depending on how far Electrum-Dash has diverged.

**Comment by Kefkius** [comment]
There are some tentative plans to merge the upstream changes of Electrum-Bitcoin into Electrum-Dash. It's behind a couple of items in the queue but the intentions are there.

**Comment by ashmoran** [comment]
Good to hear :) 

I remembered another nice feature in 2.6, you only have to enter your Trezor password once when accessing an existing wallet. A small feature, but extremely useful if you have a long password!

**Comment by schinzelh** [comment]
This is fixed with #53 and #54 - we are now even with Electrum 2.6.4

**Comment by ashmoran** [comment]
That's excellent news, I look forward to the downloads!
