### ISSUE TITLE
Exception in thread: masternode_manager.py

### ISSUE THREAD

**Issue by splawik21** [dashpay/electrum-dash#27]
During the testing on windows build 0c32e9c I noticed some freeze moments and got this in the debug window.
![electrum1](https://cloud.githubusercontent.com/assets/14001049/15742698/deac1b42-28c0-11e6-9406-9667dd9ec247.png)

**Comment by schinzelh** [comment]
ping @Kefkius

**Comment by Kefkius** [comment]
I've also gotten this. It happens when you use an Electrum-DASH server which doesn't support the latest masternode functionality.

Freeze moments shouldn't be a result though.

**Comment by schinzelh** [comment]
Can we catch the exception and tell the user he is connected to a "wrong" server?

Re. dashd versions: I am afraid there may be some more changes in 12.1 client. Maybe @UdjinM6 can diff them out?

**Comment by Kefkius** [comment]
I've been able to reproduce the error and fix it with #29 

@schinzelh It's not necessarily a "wrong" server, it's just a change in the format of the proposals list.

**Comment by schinzelh** [comment]
Cool, building a new version and waiting for @splawik21 to test

@Kefkius got it :)

**Comment by Kefkius** [comment]
@schinzelh Alright. About the report of freezing: My best guess is that the user is running Electrum-DASH in a VM or with a CPU that has limited threading capabilities. If that is the case, then a similar "freezing" should happen during transaction signing and broadcasting.

**Comment by splawik21** [comment]
@Kefkius nope, no freezing with the new version, this is not a VM and is a good hardware too.
Please check my latest issue https://github.com/dashpay/electrum-dash/issues/30

**Comment by schinzelh** [comment]
It seems this has been resolved by proper exception handling, can the ticket be closed?
