### ISSUE TITLE
Masternode Activation KO

### ISSUE THREAD

**Issue by splawik21** [dashpay/electrum-dash#28]
After filling all the data neccesary in the wallet/masternodes and after activation I get this info, check the attached file, and the masternode is not seen in the network. (the windows "Signing Masternode Announce" does not disappear)

![electrum3](https://cloud.githubusercontent.com/assets/14001049/15751309/f4b9d5a4-28e9-11e6-8bdc-ab5953b725ba.png)

**Comment by Kefkius** [comment]
I'm not really sure what you're describing. Is it that after activating your masternode, it isn't seen on the network?

**Comment by splawik21** [comment]
Yes, trying to force the connection on the server which supports trezor meaby this is the reason why it is not seen and freeze times.

**Comment by Kefkius** [comment]
This could be a result of #27 so we'll focus on that for the moment.

**Comment by splawik21** [comment]
All is fine and ready for the 12.1 mainnet release. Thnx
