### ISSUE TITLE
problems with the button Tools/Preferences

### ISSUE THREAD

**Issue by cryptocity** [dashpay/electrum-dash#3]
In version 2.9.3.1+ Win10 stopped clicking the button Preferences and I can not get into the settings.
The problem occurs when you turn on to show FX rate and FIAT, after you turn it on - the menu Preferences is unavailable anymore. 
When I press it - nothing happens, other buttons in Tools and other menu work without problems.

I reinstalled the wallet but the problem still exists, where does the wallet stores the settings?

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
