### ISSUE TITLE
Activating the masternode with trezor: Error response: code 32601

### ISSUE THREAD

**Issue by splawik21** [dashpay/electrum-dash#30]
On build e744161 while activating the masternode via trezor getting the error as below.

![electrum5](https://cloud.githubusercontent.com/assets/14001049/15757209/c84ae3da-2904-11e6-89dc-939e29f60d30.png)

**Comment by schinzelh** [comment]
Is there a message in the console too?

**Comment by splawik21** [comment]
No, the console is fine, no messagges at all.

**Comment by splawik21** [comment]
Is this issue be based on the trezor firmware which yet was not out?

**Comment by thelazier** [comment]
The issue would be solved if the electrum server connect to dashd v0.12.1.x running on mainnet.

**Comment by Kefkius** [comment]
As @thelazier said, the message means that the problem is with the server, not the client. Earlier versions of dashd don't have the `masternodebroadcast` RPC.

I think the best option is to increment electrum-dash-server's version and require servers of at least that version in Electrum-DASH.

**Comment by schinzelh** [comment]
@Kefkius good idea, the client needs to have a way to identify servers which are capable of doing `masternodebroadcast`.

Dash Core client is using "service bits" in the handshake to inform the network of its capabilities, would this be a solution for Electrum-Dash server as well? Or do we want to rely on good acting server admins to

a) increase version
b) install dashd 0.12.1

**Comment by Kefkius** [comment]
Whatever we do, we'll have to rely on server admins to act honestly. The server's version is requested by the client and any response can be given.

I intend to take this version-based approach to interacting with a server from the client.

**Comment by schinzelh** [comment]
You are right, Electrum server admins are to be trusted anyway. So version string may be sufficient.

**Comment by splawik21** [comment]
Connecting to electrum.dash.siampm.com and activating the node does now cause the issue anymore.
