### ISSUE TITLE
Error: "TrezorWallet" object has no attribute 'plugin'

### ISSUE THREAD

**Issue by splawik21** [dashpay/electrum-dash#32]
Build #33
When signing the tx getting this error.

Using standard wallet, not trezor.

![electrum7](https://cloud.githubusercontent.com/assets/14001049/15794513/9118c480-29eb-11e6-8f5f-fa2f29fe53cf.png)

**Comment by Kefkius** [comment]
For `sign_transaction` of a TrezorWallet to be called, the `wallet` attribute of the main window would be a TrezorWallet. Are you positive that no trezor wallet was open?

**Comment by splawik21** [comment]
To be honest that was strange, I`ve created fresh standard wallet, send some funds from trezor into new wallet and the sign_transaction worked smoothly.

**Comment by Kefkius** [comment]
That's a relief. :D
