### ISSUE TITLE
Invalid coin name

### ISSUE THREAD

**Issue by rockandruby** [dashpay/electrum-dash#4]
When I try to sign multisig transaction with trezor I get 'Invalid coin name'. I use trezor one 1.6.2 firmware, Ubuntu 16.04 and electrum-dash 3.2.2

**Comment by rockandruby** [comment]
should be
`def get_coin_name(self):
        return "DashTestnet" if constants.net.TESTNET else "Dash"`
should be
`def get_coin_name(self):
        return "Dash Testnet" if constants.net.TESTNET else "Dash"`
so add space between Dash Testnet

**Comment by akhavr** [comment]
Fixed in https://github.com/akhavr/electrum-dash/blob/086181af9f9ce85826d4bf3e551a5398c419ced3/electrum_dash/plugins/trezor/trezor.py#L156
