### ISSUE TITLE
This document wiki page is outdated need replacement ASAP

### ISSUE THREAD

**Issue by thelazier** [dashpay/electrum-dash#44]
Please replace this link as soon as possible, it's currently link to some advertisments and may possibly contain malwares.
**http://electrum.orain.org/**

https://github.com/dashpay/electrum-dash/blob/a9b82e96d264ed958ffa8ed96d5c303757cdc7b0/gui/qt/main_window.py#L468

**Comment by schinzelh** [comment]
Good find, fixed in #45
