### ISSUE TITLE
update bundled dependency of python-trezor to at least version 0.6.13

### ISSUE THREAD

**Issue by prusnak** [dashpay/electrum-dash#47]
... for windows builds

this fixes issues with firmware 1.3.6 (it is unusable with older python-trezor) on windows

**Comment by splawik21** [comment]
Have the same problem.
 
![electrum firmware updated 54 build](https://cloud.githubusercontent.com/assets/14001049/16361690/fcf70428-3b98-11e6-8731-48cace4e1ad8.png)

**Comment by schinzelh** [comment]
I'll rebuild Electrum with python-trezor 0.6.13

@prusnak Any chance you start tagging your releases in git? I've noticed you just bump the version without tagging it.

--> https://github.com/trezor/python-trezor/commit/f9d82511f2987c4ef74b6439276a43016257798a

**Comment by schinzelh** [comment]
Test build available at https://dashpay.atlassian.net/builds/browse/ELMW-DEV-56/artifact/JOB1/electrum-dash.exe/electrum-dash.exe

**Comment by splawik21** [comment]
Getting this one and the client does not open itself.

![electrum 56 build](https://cloud.githubusercontent.com/assets/14001049/16361883/f555c2a8-3b9e-11e6-85b1-cb158c506366.png)

**Comment by splawik21** [comment]
Getting this one and the client does not open itself

![electrum 56 build](https://cloud.githubusercontent.com/assets/14001049/16361891/1a9e5e8a-3b9f-11e6-802d-ed34806162fc.png)

**Comment by schinzelh** [comment]
https://dashpay.atlassian.net/builds/browse/ELMW-DEV-58/artifact/JOB1/electrum-dash.exe/electrum-dash.exe

**Comment by schinzelh** [comment]
I am on firmware 1.3.5 - does not work either

**Comment by schinzelh** [comment]
I guess the plugin API has changed and python-trezor-0.6.13 is not compatible with Electrum-Dash 2.4.2

@Kefkius any idea?

**Comment by prusnak** [comment]
> @prusnak Any chance you start tagging your releases in git? I've noticed you just bump the version without tagging it.

I can start doing it, but we upload releases to PyPI and I though that's the place where everyone is getting them from.

**Comment by Kefkius** [comment]
@prusnak I don't think there's a way (if there is one I certainly haven't found it) to look at diffs between versions on PyPI, which is what we're looking for.

@schinzelh Trezor wallet loads on Linux with firmware 1.3.6 and python-trezor 0.6.13. Could it be an issue with how your builds are done?

**Comment by prusnak** [comment]
With windows there never was a problem (even with older python-trezor). Whole fix is just for Windows.

**Comment by schinzelh** [comment]
We are on Electrum 2.4.2 codebase - so my educated guess is that python-trezor-0.6.13 is not compatible with Electrum 2.4 due to some plugin API changes.

**Comment by prusnak** [comment]
And I am telling you that the breakage must have happened earlier, you just have not noticed it.

**Comment by schinzelh** [comment]
Hmm, then I'll test all versions of python-trezor from 0.6.7 up to 0.6.13 to find were we broke.

We were using python-trezor-0.6.7 before (which worked) before updating to python-trezor-0.6.13 (which does not) - so good chance the bug was introduced along the way.

I'll keep you posted.

**Comment by prusnak** [comment]
Thank you!

**Comment by prusnak** [comment]
I studied the issue further and these kinds of bugs appear when one workflow does not eat all messages sent by TREZOR from the queue. New workflow sees message from older workflow and it is understandably not the message it expects.

**Comment by schinzelh** [comment]
That makes sense. I'll have a look at the workflow as well

**Comment by prusnak** [comment]
Btw, we just released python-trezor 0.7.0 with some refactored parts. No big functional changes were between 0.6.13 and 0.7.0, but when you'll be updating your binaries, please use 0.7.0 instead.

Also I tagged the release commit in Git.

**Comment by Kefkius** [comment]
That explains why the error in https://github.com/dashpay/electrum-dash/issues/47#issuecomment-228594459 is thrown [here](https://github.com/dashpay/electrum-dash/blob/develop/plugins/trezor.py#L142) (re: unexpected messages)

**Comment by prusnak** [comment]
I reported incorrectly to use 0.7.0.
  
Please use 0.6.13, because newer branch requires some further changes to
your codebase.

**Comment by schinzelh** [comment]
Thanks for the pointer :+1:

**Comment by prusnak** [comment]
Btw, any particular reason why you don't follow Electrum development and stick to the obsolete 2.4 branch? Doing that would so much things easier for you. (Electrum-Ltc had patched binaries ready in a couple of minutes).

**Comment by schinzelh** [comment]
No particular reason, just lack of time and resources :-)

I am still in the process merging us up to upstream

**Comment by Kefkius** [comment]
> Also I tagged the release commit in Git.

@prusnak I'm not seeing any tags in https://github.com/trezor/python-trezor. Isn't that the right repo?

**Comment by prusnak** [comment]
Sorry, try again. Forgot to push using --tags.

**Comment by schinzelh** [comment]
We have successfully updated to Electrum 2.6.4 codebase and python-trezor-0.6.13 now

Many thanks!
