### ISSUE TITLE
[Android] Add to F-Droid

### ISSUE THREAD

**Issue by PanderMusubi** [dashpay/electrum-dash#5]
Similarly to https://github.com/spesmilo/electrum/issues/1700 and https://gitlab.com/fdroid/rfp/issues/188 , there is also a request for packaging this fork for Dash of Electrum for F-Droid, see https://gitlab.com/fdroid/rfp/issues/817

**Comment by nmarley** [comment]
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.
