### ISSUE TITLE
Electrum not working

### ISSUE THREAD

**Issue by b1sheo** [dashpay/electrum-dash#65]
Electrum-DASH cannot connect to the server, so remains offline. It apperas to happen today, and my wallet is still unusable

**Comment by schinzelh** [comment]
ping @thelazier

**Comment by thelazier** [comment]
my server is serving 33 sessions with 3 peers connected, all seems working well. May I have your error message/screen shots ?
please also try manual connect to electrum.dash.siampm.com port 50002 (with ssl checked) if possible.

**Comment by b1sheo** [comment]
Now its working as expected without any additional actions on my side.
However, before that, it showed me no error message, just "Syncronizing" and then "Offline".
Also i tried manual connects, and it didn't work.
Thanks!
