### ISSUE TITLE
2 electrum-servers not work

### ISSUE THREAD

**Issue by Reedych456** [dashpay/electrum-dash#9]
drk1.electrum-servers.us and electrum.darkcointalk.org not work
Please add my server: 109.120.190.22

**Comment by guruvan** [comment]
Definitely should get more servers added to  source right away. Thank you. 

On February 16, 2016 10:21:07 PM PST, Reedych <notifications@github.com> wrote:
>drk1.electrum-servers.us and electrum.darkcointalk.org not work
>Please add my server: 109.120.190.22
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dashpay/electrum-dash/issues/9

-- 
Rob Nelson
guruvan@maza.club
530.859.3794

**Comment by guruvan** [comment]
Fixed in PR #10
