### ISSUE TITLE
Electrum  client stopped working 

### ISSUE THREAD

**Issue by staier** [dashpay/electrum-dash#91]
Was there  a mandatory update ? is 2.5.1 or upper officially  released?
![screenshot from 2017-02-15 17 49 02](https://cloud.githubusercontent.com/assets/1745233/22985278/a898a208-f3b0-11e6-87dd-8d8c726b5225.png)

**Comment by kryztoval** [comment]
I think you need to get it from git sources to get the latest version. You will end up having version 2.6.4 if you do that.

**Comment by kryztoval** [comment]
I see you use Mint, which is based in Debian/Ubuntu.
Here are the steps I used to run the latest client in Debian

git clone https://github.com/dashpay/electrum-dash.git
cd electrum-dash
sudo apt-get install python-qt4 python-pip python2.7-dev pyqt4-dev-tools wget
wget http://anh.cs.luc.edu/331/code/aes.py
sudo pip install ecdsa qrcode pbkdf2 protobuf jsonrpclib x11_hash
pyrcc4 icons.qrc -o gui/qt/icons_rc.py
./electrum-dash

**Comment by staier** [comment]
i  have no problem  installing  new version .
However  official  release is still 2.4.1
ok. understood.
