### ISSUE TITLE
2 Dash lost with Electrum Dash...

### ISSUE THREAD

**Issue by yassutaro** [dashpay/electrum-dash#95]
Hello friends, greetings!

I have installed Electrum Dash version 2.4.1 on my computer (Windows 10). Select the network manually for "electrum.masternode.io", I left the rate on the automatic, however, I can only receive Dash. When trying to send, no confirmation is obtained and my dash gets lost in space time. I have read several tutorials in forums, about trying to import my wallet into other applications, but none of them, because my sentence contains 13 words. They all support only 12. Is this an aberration, I was awarded? I did not find any that would allow me to import the private keys and I'm starting to think that I lost over 40 dollars when opting for Electrum. I've read that there is no way to cancel the upload, just try to duplicate to overlap through another wallet, but I can not even import it into other ...
I am in this situation for several days. I tried to import with Exodus and Jaxx without success. Currently I keep the Dash that I have left in Jaxx. Is it possible to resolve this problem? I have not seen anyone yet who has succeeded in this. I've met countless people who lost their Dash forever with Electrum. Could you help me, please?
Thank you and a big hug to the whole community!

_P.S. Errors due to Google Translator ... : D_

**Comment by thelazier** [comment]
try this unreleased version of electrum-dash for windows  https://dashpay.atlassian.net/builds/browse/ELMW-DEV/latestSuccessful/artifact/JOB1/electrum-dash.exe/electrum-dash.exe

**Comment by yassutaro** [comment]
Thank you so much for the help so fast!
I downloaded and executed the file as administrator, but the screen remains in a prompt where I can not write. Forgive my ignorance, but even if I could write, I do not know any command ... I do not know what the next step is.

**Comment by thelazier** [comment]
wait for the gui :)

**Comment by yassutaro** [comment]
Sorry for the anxiety ...: D
The most recent submission attempt, of smaller value has disappeared, however, the 1.8 dash remains with the same status.

**Comment by thelazier** [comment]
Possibly try new/restore from seed into new wallet file so you could try make new transaction on new electrum-dash version.

**Comment by yassutaro** [comment]
That's what I did. Before running this version you sent me, I uninstalled the previous one and when I ran this one, I created a new one from the seed. The second minor value operation "0.03471666" disappeared. The 1.8891 dash value remains unconfirmed. I have refined the smaller one and it remains "unconfirmed" again.

**Comment by thelazier** [comment]
Please self-invite to https://dash-nation-invite.herokuapp.com/ and get more help from communities.

**Comment by yassutaro** [comment]
Hello ... Before resorting to the community, I decided to insist a little here. I did the following: Exit the application, I went to the folder "C: \ Users \" myuser "\ AppData \ Roaming \ Electrum-DASH" and deleted all the created portfolios. In re-run unreleased version, I created a new wallet and imported the private keys with the seed. Once he had loaded all the previous transactions they had disappeared. I put the maximum rate (far right), left the server configured as automatic, and reissued the send operation. It worked!!!
I was able to recover the dash I already thought were lost! I hope this information helps others who are going through it. I will go to the other forums to share this solution to try to help those who have not yet succeeded.
Thank you very much for your help and for the kindness to respond so promptly!
A big hug to you, the whole team and enthusiastic community of the DASH.

**Comment by fyipal** [comment]
Windows exe works. Mac ppl try installing this on window vm and move your dash to some other wallet. (Thats what i did. Try "Exodus")https://dashpay.atlassian.net/builds/browse/ELMW-DEV/latestSuccessful/artifact/JOB1/electrum-dash.exe/electrum-dash.exe

**Comment by jors7** [comment]
Hello guys, I have the same problem... The installation file with the latest version doesn't work and no tips you mentioned above doesn't work for me as well.... I am lost.

Does it mean I lost all my money in Dash or you finally find the solution?
